### ISSUE TITLE
Ipss.plugin.jar lib may be outdated, and caused errors 

### ISSUE THREAD

**Issue by thuang** [InterPSS-Project/ipss-common#12]
Ipss.plugin.jar lib may be outdated, and caused errors below. They are not observed when running the program while referencing to the sources of ipss.plugin.core and ipss.plugin.base instead of the libs.
---------------------------------------

java.lang.ClassCastException: org.ieee.odm.schema.PSXfrShortCircuitXmlType cannot be cast to org.ieee.odm.schema.XfrShortCircuitXmlType
	at org.interpss.mapper.odm.impl.acsc.AbstractODMAcscParserMapper.setAcscBranchData(AbstractODMAcscParserMapper.java:441)
	at org.interpss.mapper.odm.impl.acsc.AbstractODMAcscParserMapper.map2Model(AbstractODMAcscParserMapper.java:164)
	at org.interpss.mapper.odm.impl.aclf.AbstractODMAclfParserMapper.map2Model(AbstractODMAclfParserMapper.java:125)

**Comment by jinjingfarm** [comment]
@thuang with the new commit 

https://github.com/InterPSS-Project/ipss-plugin/commit/3dc23abe852a695316853c43f290ba497edfcc26 

I am getting the following compiling error when trying to run the testcase: org.interpss.core.dstab.DStab_IEEE9Bus_Test 

com.interpss.common.exp.InterpssRuntimeException: Method not implemented
	at com.interpss.dstab.cache.StateVariableRecorder.getOutputVarIdList(StateVariableRecorder.java:346)
	at com.interpss.dstab.algo.defaultImpl.DStabSolverImpl.procInitOutputEvent(DStabSolverImpl.java:243)
	at com.interpss.dstab.algo.defaultImpl.AbstractDStabSolver.initialization(AbstractDStabSolver.java:53)
	at com.interpss.dstab.algo.impl.DynamicSimuAlgorithmImpl.initialization(DynamicSimuAlgorithmImpl.java:655)
	at org.interpss.core.dstab.DStab_IEEE9Bus_Test.IEEE9_Dstab_benchMark(DStab_IEEE9Bus_Test.java:240)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

**Comment by thuang** [comment]
@jinjingfarm  The error you observed is not related to AclfBranchHelper. It is related to the StateVariableRecorder class. I will fix that.

I got another error when I used Ipss.plugin.jar lib. This is another indication the lib is not  built with the latest code (I don't see this issue when run with source code)

Jun 12, 2019 4:26:12 PM org.interpss.mapper.odm.impl.acsc.AbstractODMAcscParserMapper map2Model
SEVERE: Error: only acsc<Branch> could be used for SC study.

**Comment by thuang** [comment]
@jinjingfarm Please see this fix for the issue you reported [https://github.com/interpss/core/commit/ca3cd5aa8215cfdc01d98e5f45b6458a45511959](url)

**Comment by jinjingfarm** [comment]
@thuang rebuilt the ipss jar files. Please give a try.

**Comment by thuang** [comment]
The Problem is fixed with the latest update
