### ISSUE TITLE
DStab_IEEE39Bus_Test.java fail to run

### ISSUE THREAD

**Issue by chenjie8809** [InterPSS-Project/ipss-common#7]
Run as JUnit Test with the java file:  ipss-common/ipss.tutorial/org.interpss.tutorial.ch2_dstab/DStab_IEEE39Bus_Test.java，output in Console View is as follows:   
Invalid line, line# 9,:
Invalid line, line# 10,:
Invalid line, line# 19,:
Invalid line, line# 20,:
Invalid line, line# 30,:
Invalid line, line# 31,:
Invalid line, line# 43,:
Invalid line, line# 44,:
Invalid line, line# 53,:
Invalid line, line# 54,:                 
Invalid line, line# 63,:
Invalid line, line# 64,:
Invalid line, line# 76,:
Invalid line, line# 88,:
Invalid line, line# 98,:               
Invalid line, line# 99,:
Invalid line, line# 101,:

**Comment by DonghaoFeng** [comment]
the trace as follow ：
java.lang.NoClassDefFoundError: com/interpss/core/acsc/impl/BaseAcscBusImpl
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.interpss.dstab.impl.DstabFactoryImpl.createDStabBus(DstabFactoryImpl.java:130)
	at com.interpss.DStabObjectFactory.createDStabBus(DStabObjectFactory.java:147)
	at com.interpss.DStabObjectFactory.createDStabBus(DStabObjectFactory.java:166)
	at org.interpss.mapper.odm.impl.dstab.AbstractODMDStabParserMapper.map2Model(AbstractODMDStabParserMapper.java:131)
	at org.interpss.tutorial.ch5_dstab.DStab_IEEE9Bus_Test.test_IEEE9Bus_Dstab(DStab_IEEE9Bus_Test.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.ClassNotFoundException: com.interpss.core.acsc.impl.BaseAcscBusImpl
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 52 more

**Comment by jinjingfarm** [comment]
With the new ipss.lib update, the issue should be resolved.

https://github.com/InterPSS-Project/ipss-common/commit/4e9725145860903ac5e09ded61009207f6f212a7

Now the DStab_IEEE9Bus_Test can pass the Unit Testing. However, we still have problems to run IEEE39_Dstab_benchMark. A separate issue will be opened on this issue.
