### ISSUE TITLE
Issue with running IEEE39_Dstab_benchMark.java 

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss-common#8]
@thuang After upgrading the ipss.lib, we got the following error when running the IEEE39_Dstab_benchMark tutorial sample. 

```
Invalid line, line# 9,:
Invalid line, line# 10,:
Invalid line, line# 19,:
Invalid line, line# 20,:
Invalid line, line# 30,:
Invalid line, line# 31,:
Invalid line, line# 43,:
Invalid line, line# 44,:
Invalid line, line# 53,:
Invalid line, line# 54,:                 
Invalid line, line# 63,:
Invalid line, line# 64,:
Invalid line, line# 76,:
Invalid line, line# 88,:
Invalid line, line# 98,:               
Invalid line, line# 99,:
Invalid line, line# 101,:


                          Load Flow Summary

                         Max Power Mismatches
             Bus              dPmax       Bus              dQmax
            -------------------------------------------------------
            Bus16            0.000000  Bus13            0.000000 (pu)
                            0.0002120                   0.000975 (kva)

     BusID          Code           Volt(pu)   Angle(deg)     P(pu)     Q(pu)      Bus Name   
  -------------------------------------------------------------------------------------------
java.lang.ClassCastException: com.interpss.dstab.impl.DStabBusImpl cannot be cast to com.interpss.core.aclf.AclfBus

                  PV Bus Limit Adjustment/Control

      BusID     Vact     Vspec      Q      Qmax     Qmin   Status
     -------- -------- -------- -------- -------- -------- ------
     Bus30      1.0475   1.0475     1.46    99.00   -99.99    on
     Bus32      0.9831   0.9831     2.05    99.00   -99.99    on
     Bus33      0.9972   0.9972     1.10    99.00   -99.99    on
     Bus34      1.0123   1.0123     1.66    99.00   -99.99    on
     Bus35      1.0493   1.0493     2.12    99.00   -99.99    on
     Bus36      1.0635   1.0635     1.01    99.00   -99.99    on
     Bus37      1.0278   1.0278     0.00    99.00   -99.99    on
     Bus38      1.0265   1.0265     0.23    99.00   -99.99    on
     Bus39      1.0300   1.0300    -1.62    99.00   -99.99    on


                          Tap Voltage Adjustment/Control

          BranchID     VC BusID  Actual   Spec/Range     Tap  Tmax  Tmin  StepSize Status
     ----------------- -------- -------- -------------- ----- ----- -----   -----  ------
     Bus6->Bus31(1)    Bus6       1.0077 ( 1.17, 0.91 ) 1.070 1.100 0.900       0      on

May 17, 2018 8:42:26 PM com.interpss.dstab.controller.annotate.AbstractAnnotateController parseAnnotation
SEVERE: Language error in controller field annotation description. 
 com.interpss.common.exp.InterpssException: Can't find field krDelayBlock implements IControlBlock, java.lang.NoSuchFieldException: krDelayBlock
com.interpss.common.exp.InterpssException: Can't find field krDelayBlock implements IControlBlock, java.lang.NoSuchFieldException: krDelayBlock
	at com.interpss.dstab.controller.annotate.AbstractAnnotateController.getControlBlockField(AbstractAnnotateController.java:238)
	at com.interpss.dstab.controller.wrapper.ControlBlockFieldAnWrapper.createObject(ControlBlockFieldAnWrapper.java:71)
	at com.interpss.dstab.controller.annotate.AbstractAnnotateController.parseAnnotation(AbstractAnnotateController.java:530)
	at com.interpss.dstab.controller.annotate.AbstractAnnotateController.initStates(AbstractAnnotateController.java:294)
	at org.interpss.dstab.control.exc.ieee.y1968.type1.Ieee1968Type1Exciter.initStates(Ieee1968Type1Exciter.java:192)
	at com.interpss.dstab.mach.impl.DynamicMachineImpl.initStates(DynamicMachineImpl.java:409)
	at com.interpss.dstab.impl.BaseDStabNetworkImpl.initDStabNet(BaseDStabNetworkImpl.java:751)
	at com.interpss.dstab.algo.defaultImpl.AbstractDStabSolver.initialization(AbstractDStabSolver.java:46)
	at com.interpss.dstab.algo.impl.DynamicSimuAlgorithmImpl.initialization(DynamicSimuAlgorithmImpl.java:590)
	at org.interpss.tutorial.ch5_dstab.DStab_IEEE39Bus_Test.IEEE39_Dstab_benchMark(DStab_IEEE39Bus_Test.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
May 17, 2018 8:42:26 PM com.interpss.dstab.mach.impl.DynamicMachineImpl initStates
SEVERE: Error: The exciter init States failed, machine :Bus30-mach1
May 17, 2018 8:42:26 PM com.interpss.dstab.controller.annotate.AbstractAnnotateController parseAnnotation
SEVERE: Language error in controller field annotation description. 
 com.interpss.common.exp.InterpssException: Can't find field krDelayBlock implements IControlBlock, java.lang.NoSuchFieldException: krDelayBlock
com.interpss.common.exp.InterpssException: Can't find field krDelayBlock implements IControlBlock, java.lang.NoSuchFieldException: krDelayBlock
	at com.interpss.dstab.controller.annotate.AbstractAnnotateController.getControlBlockField(AbstractAnnotateController.java:238)
	at com.interpss.dstab.controller.wrapper.ControlBlockFieldAnWrapper.createObject(ControlBlockFieldAnWrapper.java:71)
	at com.interpss.dstab.controller.annotate.AbstractAnnotateController.parseAnnotation(AbstractAnnotateController.java:530)
	at com.interpss.dstab.controller.annotate.AbstractAnnotateController.initStates(AbstractAnnotateController.java:294)
	at org.interpss.dstab.control.exc.ieee.y1968.type1.Ieee1968Type1Exciter.initStates(Ieee1968Type1Exciter.java:192)
	at com.interpss.dstab.mach.impl.DynamicMachineImpl.initStates(DynamicMachineImpl.java:409)
	at com.interpss.dstab.impl.BaseDStabNetworkImpl.initDStabNet(BaseDStabNetworkImpl.java:751)
	at com.interpss.dstab.algo.defaultImpl.AbstractDStabSolver.initialization(AbstractDStabSolver.java:46)
	at com.interpss.dstab.algo.impl.DynamicSimuAlgorithmImpl.initialization(DynamicSimuAlgorithmImpl.java:590)
	at org.interpss.tutorial.ch5_dstab.DStab_IEEE39Bus_Test.IEEE39_Dstab_benchMark(DStab_IEEE39Bus_Test.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
May 17, 2018 8:42:26 PM com.interpss.dstab.mach.impl.DynamicMachineImpl initStates
```

**Comment by thuang** [comment]
First, I don't have this issue when using older branches. So this issue is most likely introduced by some updates in the main branch, for example, remove of Spring framework?

The error is traced down to this function in  Ieee1968Type1Exciter.java: 
@Override public Field getField(String fieldName) throws Exception {
    	return getClass().getField(fieldName);   }

I cannot do anything on this. 

@jinjingfarm Please check it on your side.

**Comment by jinjingfarm** [comment]
The issue has been resolved with the following commit:
https://github.com/InterPSS-Project/ipss-common/commit/34f22677ab64de369c4abed0f5623effa28d2019

**Comment by jinjingfarm** [comment]
@thuang However we still see the following in the output:

```
Invalid line, line# 9,:
Invalid line, line# 10,:
Invalid line, line# 19,:
Invalid line, line# 20,:
Invalid line, line# 30,:
Invalid line, line# 31,:
Invalid line, line# 43,:
Invalid line, line# 44,:
Invalid line, line# 53,:
Invalid line, line# 54,:                 
Invalid line, line# 63,:
Invalid line, line# 64,:
Invalid line, line# 76,:
Invalid line, line# 88,:
Invalid line, line# 98,:               
Invalid line, line# 99,:
Invalid line, line# 101,:
```
Can these messages be fixed?

**Comment by jinjingfarm** [comment]
with the new ipss.lib update, all the issues have been resolved.
